ln -s left_ptr default
ln -s question_arrow help
ln -s hand2 pointer
ln -s watch wait
ln -s watch progress
ln -s xterm text
ln -s fleur move
ln -s sb_h_double_arrow ew-resize
ln -s sb_v_double_arrow ns-resize
